from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
import cv2
import asyncio
from .models import OccupancyRecord, ThresholdUpdate, StatusResponse

# Initialize the FastAPI application
app = FastAPI(title="Railway Occupancy Monitor API")

# Configure CORS so that the React frontend (running on a different port like 5173) 
# can make requests to this backend without browser security blocks.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Global state variables to hold the most recent data generated by the main detection thread.
# Since the detection engine runs in the main thread and FastAPI runs in a background thread,
# these global variables act as a simple bridge for inter-thread communication.
latest_record: OccupancyRecord | None = None
history: list[OccupancyRecord] = []
latest_frame = None

def update_frame(frame):
    """
    Updates the global state with the latest annotated frame.
    This function is called continuously by the main detection loop.
    """
    global latest_frame
    latest_frame = frame

async def generate_frames():
    """
    Generator function that yields JPEG encoded frames as a continuous byte stream.
    This creates the MJPEG (Motion JPEG) stream consumed by the frontend dashboard.
    """
    while True:
        if latest_frame is not None:
            # Compress the raw OpenCV frame into a JPEG format to save bandwidth
            ret, buffer = cv2.imencode('.jpg', latest_frame)
            if ret:
                frame_bytes = buffer.tobytes()
                # Yield the multipart HTTP response format required for MJPEG streaming
                yield (b'--frame\r\n'
                       b'Content-Type: image/jpeg\r\n\r\n' + frame_bytes + b'\r\n')
        
        # Sleep for ~33ms to cap the stream at approximately 30 FPS.
        # This prevents the server from consuming 100% CPU on an infinite tight loop.
        await asyncio.sleep(0.033) 

def update_record(record: OccupancyRecord):
    """
    Updates the global state with a new occupancy record.
    Called by the main detection loop every time a frame is processed.
    """
    global latest_record, history
    latest_record = record
    history.append(record)
    
    # Maintain a rolling window of the last 200 records to prevent memory leaks 
    # while keeping enough history for the frontend graph to display correctly.
    if len(history) > 200:
        history.pop(0)

@app.get("/")
def read_root() -> dict:
    """
    Root endpoint. Acts as a simple sanity check to verify the API is reachable.
    """
    return {"status": "running", "message": "API is live"}

@app.get("/occupancy", response_model=OccupancyRecord)
def get_occupancy():
    """
    Returns the most recent occupancy record.
    The frontend polls this endpoint to update the "Current Live Count" card.
    """
    if latest_record is None:
        raise HTTPException(status_code=404, detail="No data yet")
    return latest_record

@app.get("/history", response_model=list[OccupancyRecord])
def get_history():
    """
    Returns the last 50 records from history.
    The frontend uses this to render the historical trends graph.
    """
    return history[-50:]

@app.get("/video_feed")
async def video_feed():
    """
    Returns the continuous MJPEG video stream.
    The frontend uses this URL as the `src` attribute for an `<img>` tag.
    """
    return StreamingResponse(generate_frames(), media_type="multipart/x-mixed-replace; boundary=frame")

@app.post("/thresholds", response_model=StatusResponse)
def update_thresholds(update: ThresholdUpdate):
    """
    Accepts a POST request to dynamically update the Low/Medium/High classification thresholds.
    This modifies the global config so that the main thread picks up the new rules immediately.
    """
    # Import the global configuration object
    import config
    # Overwrite the thresholds directly
    config.LOW_MAX = update.low_max
    config.HIGH_MIN = update.high_min

    return StatusResponse(status="success", message="Thresholds updated")

@app.get("/health")
def health_check() -> dict:
    """
    Health check endpoint utilized by load balancers or docker orchestration.
    """
    return {"status": "ok"}
